#!/usr/bin/env bash

usage() {
    echo "usage: git evolution <subcommand>"
    echo
    echo "Available subcommands are:"
    echo -e "stats \tPrint out statistics about a git repository"
}

version() {
    echo "evolution git plugin v0.1.0"
    echo
}


main() {
    if [ "$#" -lt 1 ]; then
        usage; exit 1
    fi

    local subcommand="$1"; shift

    case $subcommand in
        "-h"|"--help")
            usage; exit 0
            ;;
        "-v"|"--version")
            version; exit 0
            ;;
    esac

    local workingdir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
    if [ ! -e "$workingdir/git-evolution-$subcommand" ]; then
        usage; exit 1
    fi

    source "$workingdir/git-evolution-$subcommand"
    if [ ! -n $(type -t "cmd_$subcommand") ] || [ $(type -t "cmd_$subcommand") != function ]; then
        usage; exit 1
    fi

    cmd_$subcommand "$@"
}

main "$@"
