#!/usr/bin/env bash

_commits_by_file () {
    echo 'Commits by file'
    echo
    git whatchanged --format=oneline | grep -iE "\sM\s|\sA\s|\sD\s" | cut -d " " -f 5 | cut -d$'\t' -f 2 | sort | uniq -c | sort -r
    echo
}

_lines_by_file () {
    echo 'Lines added/removed by file'
    echo
    git log --numstat --pretty="" | awk '{A[$3]+=$1;R[$3]+=$2} END { for(x in A) print "   "A[x],"\t"R[x],"\t"x }' | sort -r -n -t$'\t' -k 1,2
    echo
}

case $1 in
    "stats")
        _commits_by_file
        _lines_by_file
        ;;
esac
